export const AIActionType = Object.freeze({
    // Budget
    ADD_BUDGET_ITEM: "ADD_BUDGET_ITEM",
    UPDATE_BUDGET_ITEM: "UPDATE_BUDGET_ITEM",
    DELETE_BUDGET_ITEM: "DELETE_BUDGET_ITEM",

    // Checklist
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    DELETE_TASK: "DELETE_TASK",
    CREATE_SUBTASK: "CREATE_SUBTASK",
    UPDATE_SUBTASK: "UPDATE_SUBTASK",
    TOGGLE_SUBTASK: "TOGGLE_SUBTASK",
    DELETE_SUBTASK: "DELETE_SUBTASK",

    // Guests
    CREATE_GUEST: "CREATE_GUEST",
    CREATE_GUESTS_BULK: "CREATE_GUESTS_BULK",
    UPDATE_GUEST: "UPDATE_GUEST",
    DELETE_GUEST: "DELETE_GUEST",
    SEND_GUEST_INVITE: "SEND_GUEST_INVITE",
    SEND_BULK_INVITES: "SEND_BULK_INVITES",

    // Invitation
    CREATE_INVITATION: "CREATE_INVITATION",
    UPDATE_INVITATION: "UPDATE_INVITATION",

    // Wedding
    UPDATE_WEDDING_DETAILS: "UPDATE_WEDDING_DETAILS",
});
