export const AIActionType = Object.freeze({
    // Budget
    ADD_BUDGET_ITEM: "ADD_BUDGET_ITEM",
    UPDATE_BUDGET_ITEM: "UPDATE_BUDGET_ITEM",

    // Checklist
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    CREATE_SUBTASK: "CREATE_SUBTASK",
    TOGGLE_SUBTASK: "TOGGLE_SUBTASK",

    // Guests
    CREATE_GUEST: "CREATE_GUEST",
    SEND_GUEST_INVITE: "SEND_GUEST_INVITE",

    // Invitation
    CREATE_INVITATION: "CREATE_INVITATION",
    UPDATE_INVITATION: "UPDATE_INVITATION",

    // Wedding
    UPDATE_WEDDING_DETAILS: "UPDATE_WEDDING_DETAILS",
});
