export interface InspirationImage {
  id: string;
  url: string;
  title: string;
  category: string;
  description: string;
  tags: string[];
  style: string;
}

export const DECOR_CATEGORIES = [
  "All","Floral Decor","Table Settings","Ceremony Arch",
  "Fairy Lights","Centerpieces","Aisle Decor","Backdrop","Candle Decor",
];

export const INSPIRATION_IMAGES: InspirationImage[] = [
  // ── Floral Decor ──────────────────────────────────────────────────────────
  {
    id: "decor-1",
    url: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=800",
    title: "Grand Rose Floral Wall",
    category: "Floral Decor",
    description: "A breathtaking floor-to-ceiling floral wall made entirely of blush roses and peonies — a stunning focal point for any reception.",
    tags: ["roses","peonies","blush","luxury","reception"],
    style: "Romantic",
  },
  {
    id: "decor-2",
    url: "https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&q=80&w=800",
    title: "Bridal Floral Cascade",
    category: "Floral Decor",
    description: "Cascading greenery mixed with white orchids and baby's breath creates a dreamy suspended floral installation.",
    tags: ["orchids","greenery","white","hanging","boho"],
    style: "Bohemian",
  },
  {
    id: "decor-3",
    url: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&q=80&w=800",
    title: "Wildflower Garden Arch",
    category: "Floral Decor",
    description: "Loose wildflowers in sunset hues draped over a wooden arch for an organic, natural look.",
    tags: ["wildflowers","marigold","dahlia","rustic","outdoor"],
    style: "Rustic",
  },
  {
    id: "decor-4",
    url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800",
    title: "Peony & Eucalyptus Garland",
    category: "Floral Decor",
    description: "Soft peonies interspersed with eucalyptus create a lush garland perfect for sweetheart table edges.",
    tags: ["peonies","eucalyptus","garland","sweetheart table"],
    style: "Romantic",
  },
  {
    id: "decor-5",
    url: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&q=80&w=800",
    title: "Tropical Leaf & Bloom Mix",
    category: "Floral Decor",
    description: "Bold tropical leaves paired with anthuriums and birds-of-paradise for a dramatic, modern floral statement.",
    tags: ["tropical","anthurium","modern","bold","reception"],
    style: "Modern",
  },
  {
    id: "decor-6",
    url: "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?auto=format&fit=crop&q=80&w=800",
    title: "Enchanted Garden Pavilion",
    category: "Floral Decor",
    description: "A fully transformed outdoor pavilion with climbing roses, hanging vines, and draped white chiffon overhead.",
    tags: ["pavilion","climbing roses","vines","outdoor","enchanted"],
    style: "Romantic",
  },
  {
    id: "decor-7",
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800",
    title: "Luxury Floral Ceiling Install",
    category: "Floral Decor",
    description: "An overhead floral cloud of white and blush blooms suspended from the ceiling transforms the entire room.",
    tags: ["ceiling","cloud","overhead","luxury","installation"],
    style: "Glam",
  },

  // ── Table Settings ────────────────────────────────────────────────────────
  {
    id: "decor-8",
    url: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&q=80&w=800",
    title: "Gold & Ivory Table Setting",
    category: "Table Settings",
    description: "Crisp ivory linens with gold charger plates, crystal glassware, and a single rose stem at each place setting.",
    tags: ["gold","ivory","charger plate","crystal","elegant"],
    style: "Glam",
  },
  {
    id: "decor-9",
    url: "https://images.unsplash.com/photo-1519225495810-7517592281e2?auto=format&fit=crop&q=80&w=800",
    title: "Rustic Wooden Table Spread",
    category: "Table Settings",
    description: "Bare wooden farm tables dressed with linen runners, vintage cutlery, and mason jar candle holders.",
    tags: ["rustic","wooden","linen","mason jar","farmhouse"],
    style: "Rustic",
  },
  {
    id: "decor-10",
    url: "https://images.unsplash.com/photo-1414235077428-971145534400?auto=format&fit=crop&q=80&w=800",
    title: "Grand Banquet Tablescape",
    category: "Table Settings",
    description: "Long banquet tables laden with lush greenery runners, pillar candles, and fine china for a regal feast.",
    tags: ["banquet","greenery","china","candles","regal"],
    style: "Dramatic",
  },
  {
    id: "decor-11",
    url: "https://images.unsplash.com/photo-1471017366528-984bb07c11f7?auto=format&fit=crop&q=80&w=800",
    title: "Dessert & Sweets Table",
    category: "Table Settings",
    description: "A beautifully styled dessert table with macarons, petit fours, and floral accents for an indulgent spread.",
    tags: ["dessert","macarons","sweets","styled","floral"],
    style: "Romantic",
  },
  {
    id: "decor-12",
    url: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&q=80&w=800",
    title: "White Minimalist Setting",
    category: "Table Settings",
    description: "All-white tableware with a sprig of rosemary and personalized name cards for a modern minimalist feel.",
    tags: ["white","minimalist","modern","clean","name cards"],
    style: "Modern",
  },

  // ── Ceremony Arch ─────────────────────────────────────────────────────────
  {
    id: "decor-13",
    url: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800",
    title: "Ivory Rose Petal Arch",
    category: "Ceremony Arch",
    description: "A classic semicircular metal arch smothered in ivory garden roses and draped chiffon — pure romance.",
    tags: ["ivory","roses","chiffon","semicircle","outdoor ceremony"],
    style: "Romantic",
  },
  {
    id: "decor-14",
    url: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=800",
    title: "Outdoor Garden Arch",
    category: "Ceremony Arch",
    description: "A lush garden arch framed by manicured hedges and seasonal blooms for an elegant outdoor ceremony.",
    tags: ["garden","hedges","blooms","elegant","outdoor"],
    style: "Modern",
  },
  {
    id: "decor-15",
    url: "https://images.unsplash.com/photo-1470229722913-7c090be5c270?auto=format&fit=crop&q=80&w=800",
    title: "Geometric Gold Frame Arch",
    category: "Ceremony Arch",
    description: "A sleek hexagonal gold frame adorned with minimal florals and hanging crystals for a modern ceremony.",
    tags: ["geometric","gold","hexagon","crystal","minimal"],
    style: "Modern",
  },
  {
    id: "decor-16",
    url: "https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&q=80&w=800",
    title: "Beach Driftwood Arch",
    category: "Ceremony Arch",
    description: "Natural driftwood lashed with jute rope and ocean-inspired blooms — perfect for a beachside ceremony.",
    tags: ["driftwood","beach","coastal","jute","ocean"],
    style: "Rustic",
  },
  {
    id: "decor-17",
    url: "https://images.unsplash.com/photo-1498677231914-50df6bc884ff?auto=format&fit=crop&q=80&w=800",
    title: "Rustic Barn Arch",
    category: "Ceremony Arch",
    description: "A weathered barn doorway draped in greenery and wildflowers creates an authentic rustic ceremony backdrop.",
    tags: ["barn","rustic","wildflowers","greenery","doorway"],
    style: "Rustic",
  },

  // ── Fairy Lights ──────────────────────────────────────────────────────────
  {
    id: "decor-18",
    url: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=800",
    title: "Fairy Light Canopy",
    category: "Fairy Lights",
    description: "Thousands of warm fairy lights suspended overhead like stars, turning any venue into an enchanted sky.",
    tags: ["canopy","stars","warm white","overhead","enchanted"],
    style: "Romantic",
  },
  {
    id: "decor-19",
    url: "https://images.unsplash.com/photo-1605337227461-8eb1cf56b823?auto=format&fit=crop&q=80&w=800",
    title: "Edison Bulb String Lights",
    category: "Fairy Lights",
    description: "Vintage Edison bulbs strung across an open-air courtyard, casting a warm amber glow for evening receptions.",
    tags: ["edison","vintage","amber","outdoor","courtyard"],
    style: "Rustic",
  },
  {
    id: "decor-20",
    url: "https://images.unsplash.com/photo-1478146896981-b80fe463b330?auto=format&fit=crop&q=80&w=800",
    title: "Twinkling Dance Floor",
    category: "Fairy Lights",
    description: "Delicate string lights canopy above the dance floor create a magical, starlit atmosphere for the reception.",
    tags: ["dance floor","twinkling","canopy","reception","magic"],
    style: "Romantic",
  },
  {
    id: "decor-21",
    url: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=800",
    title: "Champagne & Fairy Light Glow",
    category: "Fairy Lights",
    description: "Soft fairy lights reflected in champagne flutes and polished surfaces create an intimate, glowing ambiance.",
    tags: ["champagne","glow","warm","intimate","reflections"],
    style: "Glam",
  },

  // ── Centerpieces ─────────────────────────────────────────────────────────
  {
    id: "decor-22",
    url: "https://images.unsplash.com/photo-1543887013-176c49c704f4?auto=format&fit=crop&q=80&w=800",
    title: "Tall Crystal Vase Centerpiece",
    category: "Centerpieces",
    description: "Towering crystal vases overflowing with white hydrangeas and trailing amaranthus for a dramatic focal point.",
    tags: ["tall","crystal","hydrangea","amaranthus","dramatic"],
    style: "Glam",
  },
  {
    id: "decor-23",
    url: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800",
    title: "Lantern & Bloom Centerpiece",
    category: "Centerpieces",
    description: "Aged gold lanterns nestled amongst lush greenery and soft pink blooms — elegant and intimate.",
    tags: ["lantern","gold","pink","intimate","elegant"],
    style: "Romantic",
  },
  {
    id: "decor-24",
    url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=800",
    title: "Submerged Orchid Vase",
    category: "Centerpieces",
    description: "Glass cylinder vases with submerged white orchids and floating candles for a sleek, contemporary look.",
    tags: ["orchid","submerged","cylinder","floating candle","modern"],
    style: "Modern",
  },
  {
    id: "decor-25",
    url: "https://images.unsplash.com/photo-1522046310824-b0a334d284fb?auto=format&fit=crop&q=80&w=800",
    title: "Lush Low Garden Cluster",
    category: "Centerpieces",
    description: "Low clusters of garden flowers in mismatched vintage vessels for an effortlessly charming tabletop.",
    tags: ["garden","vintage","mixed","low","charming"],
    style: "Rustic",
  },
  {
    id: "decor-26",
    url: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=800",
    title: "Dried Pampas Arrangement",
    category: "Centerpieces",
    description: "Sculptural dried pampas grass, wheat stalks, and proteas in terracotta pots for a modern earthy look.",
    tags: ["pampas","dried","protea","sculptural","earthy"],
    style: "Bohemian",
  },

  // ── Aisle Decor ──────────────────────────────────────────────────────────
  {
    id: "decor-27",
    url: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&q=80&w=800",
    title: "Rose Petal Aisle Runner",
    category: "Aisle Decor",
    description: "A carpet of crimson and blush rose petals creates a breathtaking aisle the couple walks down together.",
    tags: ["rose petals","crimson","runner","romantic","ceremony"],
    style: "Romantic",
  },
  {
    id: "decor-28",
    url: "https://images.unsplash.com/photo-1512496115851-a1ab392cd3aa?auto=format&fit=crop&q=80&w=800",
    title: "Candle-Lit Aisle",
    category: "Aisle Decor",
    description: "Rows of pillar candles in varying heights line the aisle, casting a golden glow for an evening ceremony.",
    tags: ["candles","pillar","golden","evening","intimate"],
    style: "Dramatic",
  },
  {
    id: "decor-29",
    url: "https://images.unsplash.com/photo-1505944270255-07bbf86e1074?auto=format&fit=crop&q=80&w=800",
    title: "Hanging Floral Pew Markers",
    category: "Aisle Decor",
    description: "Small floral bunches tied with satin ribbon hang from every pew, creating a beautifully decorated aisle.",
    tags: ["pew markers","ribbon","satin","floral","church"],
    style: "Romantic",
  },
  {
    id: "decor-30",
    url: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&q=80&w=600",
    title: "Garden Lantern Aisle Path",
    category: "Aisle Decor",
    description: "Wrought iron lanterns filled with candles and flower petals line both sides of an outdoor aisle path.",
    tags: ["lantern","iron","outdoor","petals","pathway"],
    style: "Rustic",
  },

  // ── Backdrop ──────────────────────────────────────────────────────────────
  {
    id: "decor-31",
    url: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=600",
    title: "Blush Silk Drape Backdrop",
    category: "Backdrop",
    description: "Flowing blush silk panels gracefully draped from ceiling to floor create a soft, romantic backdrop.",
    tags: ["silk","blush","drape","flowing","soft"],
    style: "Romantic",
  },
  {
    id: "decor-32",
    url: "https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&q=80&w=600",
    title: "Greenery Flower Backdrop",
    category: "Backdrop",
    description: "Dense faux boxwood hedge panels mixed with fresh blooms form a lush green wall backdrop for photos.",
    tags: ["hedge","green","boxwood","photo wall","blooms"],
    style: "Modern",
  },
  {
    id: "decor-33",
    url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=600",
    title: "Macramé Boho Backdrop",
    category: "Backdrop",
    description: "Handcrafted macramé panels with woven dreamcatchers and dried floral accents for a bohemian ceremony.",
    tags: ["macramé","boho","handcrafted","dreamcatcher","dried floral"],
    style: "Bohemian",
  },
  {
    id: "decor-34",
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600",
    title: "Gold Sequin Backdrop",
    category: "Backdrop",
    description: "Shimmering gold sequin panels catch every beam of light, adding serious glam to the sweetheart table.",
    tags: ["sequin","gold","shimmer","glam","sweetheart table"],
    style: "Glam",
  },

  // ── Candle Decor ─────────────────────────────────────────────────────────
  {
    id: "decor-35",
    url: "https://images.unsplash.com/photo-1478146896981-b80fe463b330?auto=format&fit=crop&q=80&w=600",
    title: "Floating Candle Pool",
    category: "Candle Decor",
    description: "A shallow pool of water covered in floating candles and orchid heads — a mesmerizing, ethereal installation.",
    tags: ["floating","water","orchid","ethereal","luxury"],
    style: "Romantic",
  },
  {
    id: "decor-36",
    url: "https://images.unsplash.com/photo-1498677231914-50df6bc884ff?auto=format&fit=crop&q=80&w=600",
    title: "Taper Candle Arch Display",
    category: "Candle Decor",
    description: "A dramatic arrangement of tall taper candles at varying heights on sculptural candlesticks flanking the altar.",
    tags: ["taper","candlestick","altar","dramatic","height"],
    style: "Dramatic",
  },
  {
    id: "decor-37",
    url: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=600",
    title: "Votive Cluster Table Glow",
    category: "Candle Decor",
    description: "Clusters of small votive candles in glass holders scattered across reception tables for a warm, intimate glow.",
    tags: ["votive","cluster","glass","warm","intimate"],
    style: "Romantic",
  },
  {
    id: "decor-38",
    url: "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?auto=format&fit=crop&q=80&w=600",
    title: "Lantern Candle Tree",
    category: "Candle Decor",
    description: "A decorative tree branch hung with lanterns of all sizes, each holding a glowing candle, for a magical look.",
    tags: ["lantern","branch","tree","magical","hanging"],
    style: "Rustic",
  },
  {
    id: "decor-39",
    url: "https://images.unsplash.com/photo-1605337227461-8eb1cf56b823?auto=format&fit=crop&q=80&w=600",
    title: "Pillar Candle Column",
    category: "Candle Decor",
    description: "Grand pillar candles stacked on marble plinths with rose petals scattered at the base for a regal entrance.",
    tags: ["pillar","marble","regal","entrance","column"],
    style: "Glam",
  },
  {
    id: "decor-40",
    url: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=600",
    title: "Candlelit Sweetheart Table",
    category: "Candle Decor",
    description: "An intimate sweetheart table surrounded by pillar candles, rose arrangements, and flickering votives.",
    tags: ["sweetheart table","intimate","pillar","votives","romantic"],
    style: "Romantic",
  },
  {
    id: "decor-41",
    url: "https://images.unsplash.com/photo-1512496115851-a1ab392cd3aa?auto=format&fit=crop&q=80&w=600",
    title: "Rustic Lantern Trio",
    category: "Candle Decor",
    description: "Three mismatched lanterns of different sizes grouped with moss, succulents, and baby's breath.",
    tags: ["lantern","moss","succulent","baby's breath","trio"],
    style: "Rustic",
  },
  {
    id: "decor-42",
    url: "https://images.unsplash.com/photo-1543887013-176c49c704f4?auto=format&fit=crop&q=80&w=600",
    title: "Minimalist Candle Arch",
    category: "Candle Decor",
    description: "Clean lines of white tapers arranged symmetrically along a modern arch for an understated, elegant look.",
    tags: ["minimalist","white","taper","arch","elegant"],
    style: "Modern",
  },
];
